import type { components } from '@/types/openapi'

export type Institution = components['schemas']['Institution']
export type InstitutionRequest = components['schemas']['InstitutionRequest']
export type Campus = components['schemas']['Campus']
export type CampusRequest = components['schemas']['CampusRequest']
export type Student = components['schemas']['Student']
export type AcademicYear = components['schemas']['AcademicYear']
export type AcademicPeriod = components['schemas']['AcademicPeriod']
export type GradeLevel = components['schemas']['GradeLevel']
export type Group = components['schemas']['Group']
export type AcademicArea = components['schemas']['AcademicArea']
export type Subject = components['schemas']['Subject']
export type Teacher = components['schemas']['Teacher']
export type Parent = components['schemas']['Parent']
export type UserProfile = components['schemas']['UserProfile']
export type StudentGuardian = components['schemas']['StudentGuardian']
export type GradeDirector = components['schemas']['GradeDirector']
export type RoleEnum = components['schemas']['RoleEnum']
export type Enrollment = components['schemas']['Enrollment']
export type CourseAssignment = components['schemas']['CourseAssignment']
export type Grade = components['schemas']['Grade']
export type GradingScale = components['schemas']['GradingScale']
export type AcademicIndicator = components['schemas']['AcademicIndicator']
export type PerformanceSummary = components['schemas']['PerformanceSummary']
export type Attendance = components['schemas']['Attendance']
export type DisciplinaryReport = components['schemas']['DisciplinaryReport']
export type SchoolRecord = components['schemas']['SchoolRecord']
export type AcademicIndicatorsReport =
  components['schemas']['AcademicIndicatorsReport']
export type StatusEnum = components['schemas']['StatusEnum']
