# Generated by Django 4.2.29 on 2026-04-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_academic_indicator_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['academic_year__year', 'campus_id', 'grade_level__level_order', 'name', 'pk'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
