# Generated by Django 4.2.29 on 2026-04-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_group_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['teacher', 'academic_year'], name='core_course_teacher_year_idx'),
        ),
    ]
