# Generated by Django 4.2.29 on 2026-07-29 02:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_indicator_catalogs_to_p1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recovery_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('previous_definitive_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_recoveries', to='core.teacher')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='core.grade')),
            ],
            options={
                'verbose_name': 'Grade Recovery',
                'verbose_name_plural': 'Grade Recoveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
