# Generated by Django 4.2.29 on 2026-07-30 02:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_attendance_group(apps, schema_editor):
    """Denormalize ``group`` on existing subject-level rows so group queries cover both kinds."""
    Attendance = apps.get_model("core", "Attendance")
    CourseAssignment = apps.get_model("core", "CourseAssignment")
    Attendance.objects.filter(
        group__isnull=True, course_assignment__isnull=False
    ).update(
        group_id=models.Subquery(
            CourseAssignment.objects.filter(
                pk=models.OuterRef("course_assignment_id")
            ).values("group_id")[:1]
        )
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('EXCUSED', 'Falta con excusa'), ('UNEXCUSED', 'Falta sin excusa')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'ordering': ['-date', 'student__full_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.courseassignment'),
        ),
        migrations.RunPython(backfill_attendance_group, noop),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('course_assignment__isnull', False)), fields=('student', 'course_assignment', 'academic_period'), name='uniq_attendance_student_ca_period'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('course_assignment__isnull', True)), fields=('student', 'group', 'academic_period'), name='uniq_attendance_student_group_period'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.academicperiod'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='course_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.courseassignment'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.group'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_daily_attendances', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.student'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['group', 'date'], name='core_daily_att_group_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['academic_period', 'student'], name='core_daily_att_period_stu_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('course_assignment__isnull', False)), fields=('student', 'date', 'course_assignment'), name='uniq_daily_attendance_subject_source'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('course_assignment__isnull', True)), fields=('student', 'date'), name='uniq_daily_attendance_general_source'),
        ),
    ]
