# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_daily_attendance_roll_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="faceauth_user_id",
            field=models.UUIDField(
                blank=True,
                help_text="Stable Face-Auth tenant user UUID used as SSO identity key.",
                null=True,
                unique=True,
            ),
        ),
    ]
