# Generated by Django 4.2.29 on 2026-09-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_faceauth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='bulletin_logo_left_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the crest on the left of the student bulletin.', max_length=500),
        ),
        migrations.AddField(
            model_name='institution',
            name='bulletin_logo_right_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the crest on the right of the student bulletin.', max_length=500),
        ),
    ]
